name: Initialize and Test MySQL Database

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for MySQL to Start
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Import Database Schema
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_PASSWORD }} < sql/initialize.sql

      - name: Test Database Queries
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          echo "SHOW DATABASES;" | mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_PASSWORD }}
          echo "USE monster_hunter; SHOW TABLES;" | mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_PASSWORD }}
          echo "USE monster_hunter; SELECT * FROM monsters;" | mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_PASSWORD }}
